// Generated by CoffeeScript 1.10.0
(function() {
  var BaseChild, Metafields, DiscountCode,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseChild = require('./base_child');

  Metafields = require('./metafield');

  DiscountCode = (function(superClass) {
    extend(DiscountCode, superClass);

    DiscountCode.prototype.parent = "/price_rules";

    DiscountCode.prototype.slug = "discount_code";

    DiscountCode.prototype.child = "/discount_codes";

    function DiscountCode(site) {
      DiscountCode.__super__.constructor.call(this, site);
    }

    return DiscountCode;

  })(BaseChild);

  module.exports = DiscountCode;

}).call(this);
