// Generated by CoffeeScript 1.10.0
(function() {
  var Base, PriceRule,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Base = require('./base');

  PriceRule = (function(superClass) {
    extend(PriceRule, superClass);

    PriceRule.prototype.slug = "price_rule";

    PriceRule.prototype.prefix = "/price_rules";

    function PriceRule(site) {
      PriceRule.__super__.constructor.call(this, site);
    }

    return PriceRule;

  })(Base);

  module.exports = PriceRule;

}).call(this);